import Head from "next/head";

import styles from "@/styles/Home.module.css";
import {
  Form,
  FormLayout,
  Field,
  SubmitButton,
  Card,
  CardBody,
} from "@saas-ui/react";

import { Center, Flex, Spacer } from "@chakra-ui/react";
import {
  Persona,
  PersonaContainer,
  PersonaAvatar,
  PersonaDetails,
  PersonaLabel,
  PersonaSecondaryLabel,
  PersonaTertiaryLabel,
  Presence,
} from "@saas-ui/react";

// import {
//   Sidebar,
//   SidebarSection,
//   SidebarToggleButton,
//   SidebarOverlay,
//   NavGroup,
//   NavItem,
// } from '@saas-ui/sidebar'

import usePasswordMatch from "./pwd";

export default function Home() {
  const {
    password,
    confirmPassword,
    isMatch,
    handlePasswordChange,
    handleConfirmPasswordChange,
  } = usePasswordMatch();

  const handleSubmit = (event) => {
    console.log(event);

    // Handle form submission here
  };
  return (
    <>
      <Head>
        <title>User Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <div className={styles.container}>
          <Center h="100%" w="100%">
            {/* <Card maxW="400px" margin="auto" backgroundColor={"#eeeeee"}>
              <CardBody> */}
            <Flex direction="column">
              <Flex alignItems="start" marginBlock="4">
                <Persona
                  name="Velda Kiara"
                  secondaryLabel="Pro Plan"
                  size="lg"
                  letterSpacing={"0.78px"}
                />
              </Flex>

              <Form
                onSubmit={handleSubmit}
                defaultValues={{
                  firstName: "Velda",
                  lastName: "Kiara",
                  email: "velda@gmail.com",
                }}
              >
                <FormLayout>
                  <Field
                    backgroundColor={"white"}
                    textColor={"black"}
                    name="firstName"
                    label="First Name"
                    width="20.5em"
                    rules={{ required: true }}
                  />
                  <Field
                    backgroundColor={"white"}
                    textColor={"black"}
                    name="lastName"
                    label="Last Name"
                    width="20.5em"
                    rules={{ required: true }}
                  />
                  <Field
                    backgroundColor={"white"}
                    textColor={"black"}
                    name="email"
                    label="Email"
                    type="email"
                    rules={{ required: true }}
                    width="20.5em"
                  />
                  <Field
                    fontFamily={"mono"}
                    backgroundColor={"white"}
                    textColor={"black"}
                    type="password"
                    name="password"
                    label=" New Password"
                    value={password}
                    width="18em"
                    rules={{ required: true }}
                    onChange={handlePasswordChange}
                  />
                  <Field
                    fontFamily={"mono"}
                    backgroundColor={"white"}
                    textColor={"black"}
                    type="password"
                    name="confirmPassword"
                    label="Confirm Password"
                    value={confirmPassword}
                    width="18em"
                    rules={{ required: true }}
                    onChange={handleConfirmPasswordChange}
                  />
                  {!isMatch && (
                    <p className={styles.highlight}>Passwords do not match</p>
                  )}
                  <SubmitButton marginBlockStart="10px" disableIfInvalid>
                    Save
                  </SubmitButton>
                </FormLayout>
              </Form>
            </Flex>

            {/* </CardBody>
            </Card> */}
          </Center>
        </div>
      </>
    </>
  );
}
